# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fe46f265ed3e70bcf38c4704d46f49f9dec17e613d8dd7ac7aecc1caf540b4e971977898183e4fa90ce4dd01c9360c949a1faad1044b5deca3e74eb5eb1cbc

test:
  secret_key_base: 77460821b8fd6c7d5109c781872b448ca32ce6e1edecad3af4c00eb02324f43f39a9b1bec652972485b103381bca45ef4d4a877310b4975083fdc04cf3e0ec6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
